CREATE TABLE SUGGESTIONS (
	ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(25),
	EMAIL VARCHAR(100),
	ISSUE VARCHAR(100),
	MESSAGE VARCHAR(255)
);

ALTER TABLE SUGGESTIONS ADD FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE;
