CREATE DATABASE DONOSTIA;
USE DONOSTIA;

CREATE TABLE SENSORS (
	REGISTERID INT(10) PRIMARY KEY AUTO_INCREMENT,
	SENSORID VARCHAR(25),
	LATITUDE DECIMAL(8, 6),
	LONGITUDE DECIMAL(9, 6),
	DATETIME DATETIME,
	TEMPERATURE INT(3),
	ENERGY INT(3),
	LIGHTSTATUS BIT(1)
);
