sudo service mysql start

sudo mysql -u root -p

# Inside
CREATE USER 'smartcities'@'localhost' IDENTIFIED BY 'tecnun';
exit

# With smartcities user
CREATE DATABASE SMARTCITIES;
USE SMARTCITIES;

CREATE TABLE SENSORS (
    REGISTER INT(10) PRIMARY KEY AUTO_INCREMENT,
    SENSORID VARCHAR(25),
    LATITUDE DECIMAL(8, 6),
    LONGITUDE DECIMAL(9, 6),
    TIMESTAMP DATETIME,
    TEMPERATURE INT(3),
    ENERGY INT(3),
    STATUS BIT(1)
);

# test
INSERT INTO SENSORS (SENSORID, LATITUDE, LONGITUDE, TIMESTAMP, TEMPERATURE, ENERGY, STATUS) VALUES ('00000-1', 10.112233, -100.445566, '1000-01-01 00:00:00', 80, 70, 1);